version: "3.8"
services:
  tg:
    image: cogito-tg
    container_name: cogito_tg
    build:
      context: ./client/telegram
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 7345:7345
    env_file:
      - ./client/telegram/.env
    # environment:
    #   - LEVEL_LOGGING=DEBUG
    networks:
      - reverse-proxy
      - back
    # volumes:
    # - ./logs/dices.log:/app/dices.log

  app:
    image: cogito-app
    container_name: cogito_app
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    # environment:
    #   - LEVEL_LOGGING=DEBUG
    networks:
      - back
    # volumes:
    # - ./logs/dices.log:/app/dices.log

# volumes:
#   mongo_data:
#     driver: local
#   mongo_config:
#     driver: local

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge
